/* Universal-Oracle / rpg / packs / cyberpunk.js
   Cyberpunk. Tone: neon and glass, corp gravity, deals over morals, the body as hardware. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS.cyberpunk = {
  name: "Cyberpunk",
  tone: "Neon and glass, corp gravity, the body as hardware.",

  verbs: [
    "Acquire", "Bargain", "Breach", "Bribe", "Burn", "Cache",
    "Cancel", "Chase", "Cipher", "Compromise", "Contract", "Crash",
    "Crack", "Cut", "Dance", "Deal", "Deceive", "Delete",
    "Dox", "Dump", "Encrypt", "Erase", "Extract", "Fence",
    "Frame", "Hack", "Hire", "Hijack", "Hire out", "Hunt",
    "Inject", "Install", "Intrude", "Jack in", "Leak", "Liquidate",
    "Loop", "Mask", "Negotiate", "Outbid", "Patch", "Phish",
    "Plant", "Reroute", "Reveal", "Run", "Scrub", "Sell out",
    "Shadow", "Smuggle", "Spike", "Spoof", "Stalk", "Stash",
    "Steal", "Surveil", "Tag", "Threaten", "Trace", "Upload",
  ],

  adjectives: [
    "Acid-bright", "Anonymous", "Augmented", "Backlit", "Black-market", "Bleeding-edge",
    "Branded", "Burned", "Chrome", "Compromised", "Corporate", "Counterfeit",
    "Dirty", "Doxxed", "Encrypted", "Expendable", "Flickering", "Glassy",
    "Glitching", "Gridded", "Hacked", "Holographic", "Implanted", "Iridescent",
    "Jacked", "Leaked", "Logged", "Looped", "Masked", "Metered",
    "Modded", "Monitored", "Neon", "Off-grid", "Off-the-books", "Overclocked",
    "Persistent", "Pirated", "Privatised", "Prosthetic", "Rented", "Rigged",
    "Routed", "Sanctioned", "Scrubbed", "Shadow-banned", "Shrink-wrapped", "Signed",
    "Sleek", "Slick", "Sleeved", "Spiked", "Stolen", "Streetwise",
    "Surveilled", "Synthetic", "Tagged", "Tethered", "Throwaway", "Tracked",
    "Unlicensed", "Unverified", "Wired", "Zero-day",
  ],

  nouns: [
    "Account", "AI", "Alley", "Avatar", "Backdoor", "Black ICE",
    "Brain implant", "Burner", "Cage match", "Chrome", "Cipher", "Client",
    "Clinic", "Code", "Console", "Contract", "Corp", "Credit",
    "Cypher", "Data drop", "Dealer", "Deck", "Dossier", "Driver",
    "Encryption key", "Escort", "Exec", "Extraction", "Fence", "Firewall",
    "Fixer", "Gangbanger", "Grid", "Handle", "Hideout", "Implant",
    "Job", "Junker", "Killchip", "Kiosk", "Knockoff", "Lease",
    "Leak", "Limo", "Mask", "Megabuilding", "Merc", "Net",
    "NDA", "Node", "Nomad", "Offline drop", "Patch", "Payday",
    "Penthouse", "Persona", "Plug", "Razor", "Rig", "Runner",
    "Server", "Shadow", "Shard", "Slot", "Smuggler", "Squad",
    "Stack", "Stim", "Synth", "Tag", "Tracker", "Trojan",
    "Wire", "Worm",
  ],

  names: {
    male: [
      "Akira", "Bishop", "Carlo", "Drake", "Echo", "Felix",
      "Ghost", "Hadi", "Ishin", "Jett", "Kasimir", "Lev",
      "Marcus", "Nikolai", "Otto", "Pax", "Quill", "Rafael",
      "Saito", "Tomek", "Ulrik", "Vega", "Wraith", "Zane",
    ],
    female: [
      "Akira", "Briar", "Cyra", "Domino", "Echo", "Fern",
      "Gem", "Hira", "Iko", "Jin", "Kira", "Luxe",
      "Mira", "Niko", "Onyx", "Petra", "Quinn", "Rin",
      "Saskia", "Tana", "Uma", "Vex", "Wren", "Zara",
    ],
    neutral: [
      "Apex", "Bit", "Cipher", "Drift", "Echo", "Flux",
      "Glitch", "Hex", "Ion", "Jet", "Kismet", "Lumen",
      "Mute", "Null", "Onyx", "Pixel", "Quark", "Rune",
      "Slick", "Trace", "Umbra", "Vyx", "Wraith", "Zero",
    ],
  },

  locations: [
    "A noodle bar under a corporate plaza, wifi heavy with sniffers",
    "A penthouse balcony in a building with three names",
    "A net-cafe back room rented by the hour and the lie",
    "A clinic in a sub-basement, lit by aquariums",
    "A pop-up market in a closed metro tunnel",
    "A rooftop helipad with corporate paint scraped off",
    "A pachinko parlour as a fixer's office",
    "A black clinic above a 24-hour pharmacy",
    "A valet stand outside a megabuilding club",
    "A shipping container conversion bar in a wrecked dockyard",
    "A bullet train carriage hired off-the-books",
    "A maintenance corridor behind a corporate kitchen",
    "A holo-tagged underpass at neon hour",
    "A sky-bridge between two rival arcologies",
    "A virtual private room with rented avatars",
    "A laundromat used as a money-wash front",
    "A robotaxi parked off-grid in a service alley",
    "A discount cyberware shop on the night-market level",
    "A rented squat in a half-finished building",
    "A noodle stand favoured by a gang lieutenant",
    "A corporate observation deck after closing",
    "A dance club with private comms in the bass line",
    "A self-storage unit converted to safe house",
    "A 24-hour autodoc kiosk in a parking deck",
    "A boutique pawnshop fronting for a fence",
    "A maglev platform at a station the corp doesn't list",
    "A media archive with one corrupted shelf",
    "A drone-only market in a sealed alley",
    "A salaryman dive bar, loyalty cards bought and sold",
    "A skybridge with a clear sightline to a fixer's drop",
    "A gym where deals are made between sets",
    "A motel room rented for someone who isn't going to use it",
  ],

  catalysts: [
    "A job's pay drops with no explanation",
    "An old runner's deck appears in a fence's window",
    "A face from a sealed file walks past on the street",
    "An NDA is broken via a leak with familiar fingerprints",
    "Corp security suddenly knows the safe house",
    "A burner phone rings before it should",
    "An AI persona offers a deal it shouldn't be able to make",
    "A friend's chrome starts misfiring under stress",
    "A debt collector arrives with a polite smile",
    "A package is delivered that was never ordered",
    "A bounty appears with the runner's old handle",
    "An ex-lover surfaces with corporate ID",
    "A trusted fixer cancels mid-job and won't say why",
    "A copy of a deleted file resurfaces tagged",
    "Black ICE responds to a routine ping",
    "A contract is offered that names the runner specifically",
    "A new gang leans on familiar territory",
    "A dossier on the team is forwarded by mistake",
    "A drone visibly recognises someone in the crew",
    "A loyalty bonus is offered to defect, by name",
    "An old call sign is heard on a public band",
    "A taxi takes a detour the runner did not request",
    "A scheduled payment fails and resends from a different account",
    "An informant returns from \"vacation\" too quickly",
    "A street kid hands over a dataslate as if expected",
    "A safehouse's lock has been re-keyed by someone polite enough to leave it locked",
    "A mod-clinic offers a free upgrade out of nowhere",
    "Surveillance footage glitches in a way that means it's been doctored",
    "A whisper goes around: a fixer is taking on more clients than they should",
    "An automated system sends a personal apology",
    "A handshake comes with a tracker chip in it",
    "A protest is suspiciously well-organised, in a useful direction",
    "A recommendation arrives via someone who'd never recommend",
    "A jurisdiction line shifts overnight, leaving an asset on the wrong side",
    "A targeted ad calls the runner by an old, never-published name",
  ],

  sensory: {
    hear: [
      "Bass leaking out of a club two floors up",
      "Drone props at canopy height",
      "A vending machine's looping jingle",
      "Sirens at a cordon, blocks away",
      "A foreign-language news ticker, hard to ignore",
      "Coolant fans inside the wall",
      "An autocab announcing a destination twice",
      "A chip-reader denying transaction, three times",
      "Holographic billboard chiming for attention",
      "Static between encrypted bursts on a band you shouldn't have",
      "Plasti-sole shoes on wet concrete",
      "A neon tube that's about to die buzzing",
      "Servomotors in a friend's arm",
      "An alert tone you don't recognise",
      "Crowd noise edited, like a stadium piped in",
      "A trojan loop singing through a compromised speaker",
    ],
    see: [
      "Rain through neon, all the colours wrong",
      "A line of vending machines, one missing, the gap obvious",
      "An ad targeting you specifically",
      "Drone shadows tracking across asphalt",
      "Holo-tags layered over an alley wall",
      "A ricer car under cover, plates missing",
      "A face in a passing crowd that the AR pings as wanted",
      "Smoked glass behind which a deal is happening",
      "A logo painted out and then re-painted",
      "Camera turret rotating, not quite tracking",
      "A friend's iris flicker green at the edges",
      "Steam rising from a grate, a body half-glimpsed",
      "Reflection in a polished elevator door, twice",
      "A briefcase too clean for its handler",
      "Tracker-pings registering on AR, just outside the fence",
      "An exec's badge, already lanyard-flipped to hide the name",
    ],
    feel: [
      "Static in the air before a rainstorm in the sealed district",
      "The clean cold of a chrome implant before it warms",
      "A vibration in the floor where the building shouldn't move",
      "Sweat under a synthleather jacket",
      "The pinch of a tracker still healing into the skin",
      "Concrete heat radiating after dark",
      "A handle warming under the palm",
      "Stim-edge in the jaw, teeth wanting to grind",
      "Plastic packaging that hasn't been opened",
      "Hair raising as a high-frequency rig powers up",
      "Cold ramen broth sliding past warm chopsticks",
      "Connection lag in a haptic glove",
      "Cigarette smoke breathed second-hand",
      "Fabric stiff from a wash that didn't fully take",
      "The give of a cushioned seat in a private car",
      "A momentary pulse from a hostile beacon",
    ],
    smell: [
      "Wet asphalt and ozone",
      "Synth coffee from a kiosk",
      "Burnt circuitry, faint",
      "Hot oil in a back-alley kitchen",
      "Antiseptic and chrome polish",
      "Plastic packaging just opened",
      "Cigarette and capsule menthol",
      "Soldering flux",
      "Cologne too expensive for the venue",
      "Damp concrete and faint mildew",
      "Engine grease in a parking deck",
      "Chemical perfume from a vending booth",
      "Ramen broth and chili oil",
      "Body spray badly disguising sweat",
      "Acrylic and resin from a 3D-print shop",
      "Vape clouds in mango and mint",
    ],
  },
};
