/* Universal-Oracle / rpg / packs / demon-hunters.js
   Modern occult comedic horror — small squad of underpaid exorcists, found-family
   banter, holy water in spray bottles, demons in suburbia. Inspired by The Dead
   Gentlemen's Demon Hunters: A Comedy of Terrors (deadgentlemen.com); content here
   is original genre flavour, not reproduced from any commercial deck. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS["demon-hunters"] = {
  name: "Demon Hunters (Comedy of Terrors)",
  tone: "Holy water and dad jokes; demons in the suburbs.",

  verbs: [
    "Ambush", "Argue", "Banish", "Banter", "Bargain", "Bless",
    "Bluff", "Botch", "Bullshit", "Camp", "Chant", "Chase",
    "Crack wise", "Curse", "Deflect", "Dispel", "Distract", "Dodge",
    "Eavesdrop", "Exorcise", "Fail upward", "Field", "Find out", "Gaslight",
    "Glimpse", "Goof up", "Gripe", "Heckle", "Hide", "Improvise",
    "Investigate", "Lurk", "Mark", "Misread", "Mock", "Negotiate",
    "Nope out", "Overhear", "Pivot", "Pray", "Profile", "Quip",
    "Reassure", "Recognise", "Reveal", "Roll initiative", "Salt", "Sanctify",
    "Scoff", "Screw up", "Snark", "Stake out", "Summon", "Survive",
    "Tag-team", "Threaten", "Vouch", "Ward off", "Wing it", "Wisecrack",
  ],

  adjectives: [
    "Ambushed", "Anointed", "Awkward", "Banished", "Blessed", "Botched",
    "Burned-out", "Caffeinated", "Cardboard-thin", "Cheap", "Compromised", "Cracked",
    "Cursed", "Damp", "Damned", "Demon-haunted", "Drugstore-bought", "Exhausted",
    "Fluorescent-lit", "Forsaken", "Half-trained", "Hexed", "Holy", "Hungover",
    "Improvised", "Marked", "Off-brand", "Overworked", "Possessed", "Profane",
    "Reckless", "Sanctified", "Scrappy", "Sketchy", "Smoke-stained", "Snarky",
    "Spider-webbed", "Spooked", "Sweaty", "Tense", "Tired", "Underpaid",
    "Underqualified", "Unhinged", "Unholy", "Warded", "Weary",
  ],

  nouns: [
    "Amulet", "Apartment", "Banishing kit", "Banter", "Basement", "Briefcase",
    "Burrito", "Cantrip", "Cellphone", "Chalk circle", "Chapel basement", "Cleric",
    "Coffee", "Comm device", "Confessional", "Conspiracy", "Crucifix", "Dashcam",
    "Demon", "Diner", "Dive bar", "Dollar store", "Dossier", "Drive-thru",
    "Earpiece", "Exorcism", "Exorcist", "Fakeout", "Fast-food", "Field manual",
    "Found family", "Goon", "Gospel", "Group chat", "Hellhound", "Hellmouth",
    "Holy water", "Imp", "Liaison", "Lineage", "Liturgy", "Manuscript",
    "Minion", "Mocha", "Motel", "Office park", "Pager", "Parish",
    "Pickup truck", "Plot twist", "Possession", "Pulpit", "Rectory", "Relic",
    "Rite", "Ritual", "Rosary", "Rust-belt town", "Salt circle", "Sanctum",
    "Scripture", "Seal", "Sigil", "Squad", "Stakeout", "Strip mall",
    "Suburb", "Supervisor", "Talisman", "Tape recorder", "Team", "Thrift-store armor",
    "Voicemail", "Walkie-talkie", "Ward", "Witness",
  ],

  names: {
    male: [
      "Aiden", "Brian", "Carlos", "Dwight", "Eddie", "Frank",
      "Gabe", "Hank", "Ian", "Jamal", "Keith", "Levi",
      "Mike", "Nate", "Owen", "Pete", "Quincy", "Ramon",
      "Sam", "Tony", "Uri", "Vince", "Wendell", "Zane",
    ],
    female: [
      "Abby", "Bea", "Carmen", "Diana", "Eve", "Faith",
      "Gemma", "Hannah", "Iris", "Jess", "Kim", "Lila",
      "Maddie", "Nora", "Olivia", "Pia", "Reba", "Sasha",
      "Tess", "Uma", "Val", "Whitney", "Yara", "Zoe",
    ],
    neutral: [
      "Ash", "Bo", "Cam", "Dakota", "Eli", "Frankie",
      "Gray", "Hayden", "Indigo", "Jules", "Kai", "Lane",
      "Morgan", "Noel", "Onyx", "Parker", "Quinn", "Rae",
      "Sage", "Tate", "Val", "Wynn", "Yael", "Zane",
    ],
  },

  locations: [
    "A church basement during midweek choir practice",
    "A 24-hour diner at 3am, lit too bright",
    "A motel room with the curtains nailed shut",
    "A rural sheriff's parking lot with the cruisers idle",
    "A self-storage unit rented in cash",
    "A community college rec room after hours",
    "An abandoned strip mall with one neon sign still going",
    "A gas station bathroom with someone praying inside",
    "A suburban cul-de-sac where the dog won't go past the third house",
    "A Catholic high school's empty gym",
    "A parish hall the diocese forgot about",
    "A municipal cemetery on a Tuesday",
    "A four-bay carwash open 24 hours",
    "A ferry terminal between sailings",
    "A hotel ballroom set up for a conference that isn't until tomorrow",
    "An off-ramp truckstop with too many trucks",
    "A community pool drained for the winter",
    "A retirement-home day room",
    "A megachurch lobby an hour after service",
    "A pawnshop that has more crucifixes than usual",
    "A rented box truck in a Walmart parking lot",
    "A liquor store that sells holy water in unmarked bottles",
    "A dive bar with one locked back room",
    "An abandoned bowling alley used as a forward base",
    "A carpet warehouse the team has cleared three times",
    "A rural fire station where the bell hasn't rung in years",
    "A thrift store run by quiet nuns",
    "A high school football field after hours",
    "A noodle shop in a strip mall with too few customers",
    "A laundromat with one dryer that won't stop",
  ],

  catalysts: [
    "The client's exorcism payment bounces",
    "A demon shows up to the meeting wearing a tie",
    "A team member is recognised by a possessed barista",
    "The holy water has been swapped for tap",
    "A live broadcast accidentally airs a demonic cameo",
    "A regional supervisor schedules an unannounced ride-along",
    "Group chat reveals a mole on the team",
    "A demon offers a contract suspiciously favourable to the team",
    "A possessed pop star books the team for a tour",
    "An old college roommate shows up demanding back-pay",
    "The relic burns through its sealing tape on the drive in",
    "The pastor turns out to be the demon they've been hunting",
    "A child's drawing predicts the location of the next breach",
    "The sigil book has been rebound with a different cover",
    "A demon claims diplomatic immunity",
    "The team's van stalls in front of the cathedral with bishops watching",
    "A teenage tiktoker films the team mid-exorcism",
    "An archdeacon issues a cease-and-desist for the team's branding",
    "A demon-possessed councilman holds a press conference",
    "A client tries to exorcise the team",
    "The squadron gets audited",
    "A retired hunter calls in a favour everyone forgot about",
    "A demon's union representative arrives",
    "A storm blows out every consecrated candle in the parish",
    "A team member's mother is the surprise guest at a stake-out",
    "HR delivers a 'please refrain from explosions' memo",
    "A motel manager confiscates the salt circle as a fire hazard",
    "The exorcism playlist autocorrects to a worship song",
    "A friendly demon dies and leaves the team a hellmouth in the will",
    "An old recruiter offers the team enterprise-tier pay to defect",
  ],

  sensory: {
    hear: [
      "Radio static breaking briefly into Latin",
      "A chapel bell rung once, deliberately",
      "A printer in a back office spooling on its own",
      "A teenager humming a hymn they don't know",
      "A laugh track from a TV that isn't on",
      "A drive-thru speaker giving an order no one placed",
      "A dog barking in a perfect three-beat pattern",
      "A blender starting in an empty kitchen",
      "A pulpit microphone breathing",
      "A hymn that's a half-step flat",
      "Chairs scraping in a locked room",
      "An automated phone tree without a menu",
      "A vending machine humming after closing",
      "A choir of one voice",
      "A pager going off in 1998",
      "A cellphone ringing in a pocket no one has",
    ],
    see: [
      "A crucifix turned upside down — and back, when looked at again",
      "A child's drawing of the team taped to a fridge",
      "A church candle burning blue",
      "A salt circle scuffed in three places",
      "A driver who matches the description but has the wrong tag",
      "A receipt from a transaction the team didn't make",
      "A dashcam recording with one frame missing",
      "A bishop's ring on a stranger's finger",
      "A Polaroid that develops the wrong room",
      "A demon-hunting pamphlet in a hotel nightstand",
      "An arcade machine playing the team's debrief",
      "A sigil scratched into a banker's desk",
      "A taxi dispatcher pointing at the team without using radio",
      "A 'help wanted' sign in Latin",
      "A diner cup with steam moving the wrong way",
      "A pulpit Bible open to a passage no one was teaching",
    ],
    feel: [
      "A static charge before answering a call",
      "A holy medal hot to the touch through a shirt",
      "The wrong shoulder being tapped",
      "A pressure drop you don't feel in your ears",
      "A pew warm where no one is sitting",
      "A cellphone vibrating despite Do Not Disturb",
      "A car door warm to the touch hours after parking",
      "A handshake that lingers a beat too long",
      "A pen getting heavier as you write",
      "A draft from a vent pointed straight at you",
      "A heartbeat that catches up to you across a room",
      "A coffee that doesn't cool",
      "A trigger guard sweating",
      "A collar tightening that wasn't tight",
      "A floorboard giving where it didn't yesterday",
      "A keyring magnetised when it wasn't this morning",
    ],
    smell: [
      "Frankincense in a hotel hallway",
      "Burnt toner in a sanctuary",
      "Subway-station ozone after a thunderstorm",
      "A dollar-store candle burning without a flame",
      "Hot asphalt and incense",
      "A motel pool's chlorine, indoors",
      "Cigarette smoke in a non-smoking room",
      "Wet wool and old hymn books",
      "Drugstore cologne over something rotten",
      "A donut shop at 4am",
      "Communion wine and stale popcorn",
      "Gun oil and church polish",
      "Diner coffee and antiseptic",
      "Aftershave lingering on a borrowed jacket",
      "Sulfur in the air-conditioning",
      "Burnt sage and drain cleaner",
    ],
  },

  belongings: [
    { category: "Tactical kit",       items: ["pocket-sized salt", "thrift-store cross", "pepper spray"] },
    { category: "Holy supplies",      items: ["spray bottle of holy water", "rosary in a ziploc", "blessed chalk"] },
    { category: "Tech",               items: ["walkie-talkie", "burner phone", "dashcam SD card"] },
    { category: "Concealed weapons",  items: ["snub revolver", "consecrated knife", "stun gun"] },
    { category: "Field manual",       items: ["printed exorcism rite", "demon-classification flashcards", "field journal"] },
    { category: "Civilian disguise",  items: ["convention lanyard", "company polo", "rental car keys"] },
    { category: "Survival",           items: ["protein bar", "thermos of bad coffee", "ibuprofen"] },
    { category: "Personal",           items: ["family photo", "old dog tag", "prayer card"] },
  ],
};
