/* Universal-Oracle / rpg / packs / fantasy.js
   Heroic / mythic fantasy. Tone: weight of legend, watching gods, broken oaths. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS.fantasy = {
  name: "Basic Fantasy (LOTR / D&D)",
  tone: "Heroic, mythic, the weight of legend.",

  verbs: [
    "Bargain", "Befriend", "Beguile", "Besiege", "Betray", "Bless",
    "Break", "Burn", "Bury", "Champion", "Conjure", "Counsel",
    "Curse", "Deceive", "Defy", "Disguise", "Drown", "Echo",
    "Enchant", "Endure", "Escape", "Forge", "Forsake", "Glimpse",
    "Guard", "Hunt", "Imprison", "Invoke", "Journey", "Kneel",
    "Lament", "Lay siege", "Mourn", "Offer", "Pledge", "Plunder",
    "Pray", "Prophesy", "Protect", "Pursue", "Rally", "Ransack",
    "Reveal", "Ride out", "Return", "Sacrifice", "Seek", "Shatter",
    "Shelter", "Slay", "Steal", "Summon", "Swear", "Tempt",
    "Torch", "Track", "Unmask", "Vow", "Wander", "Whisper",
  ],

  adjectives: [
    "Ancient", "Banished", "Battered", "Beloved", "Beseiged", "Bleak",
    "Blessed", "Bloodstained", "Broken", "Buried", "Cold", "Cruel",
    "Crumbling", "Cursed", "Dark", "Distant", "Doomed", "Drowned",
    "Echoing", "Elder", "Empty", "Forbidden", "Forgotten", "Forsaken",
    "Frozen", "Glimmering", "Golden", "Grim", "Haunted", "Hidden",
    "Hollow", "Holy", "Humble", "Ironbound", "Lonely", "Lost",
    "Mossy", "Mournful", "Mythic", "Noble", "Nameless", "Old",
    "Pale", "Proud", "Quiet", "Reckless", "Restless", "Ruined",
    "Sacred", "Savage", "Secret", "Shattered", "Silent", "Sleeping",
    "Solemn", "Sworn", "Twilight", "Unspoken", "Wandering", "Weary",
  ],

  nouns: [
    "Alliance", "Banner", "Beast", "Bell", "Blade", "Bloodline",
    "Bond", "Bridge", "Cairn", "Castle", "Ceremony", "Champion",
    "Chronicle", "Citadel", "Cloak", "Companion", "Council", "Crown",
    "Curse", "Dawn", "Deed", "Dragon", "Dream", "Dwarf",
    "Elf", "Empire", "Errand", "Exile", "Fellowship", "Forest",
    "Fortress", "Gate", "Gift", "Grave", "Heir", "Herald",
    "Hidden path", "Holy place", "Hunter", "Inn", "Kin", "King",
    "Knight", "Library", "Map", "Memory", "Messenger", "Oath",
    "Omen", "Orc", "Pilgrim", "Promise", "Quest", "Queen",
    "Relic", "Ring", "Ruin", "Seer", "Sigil", "Song",
    "Standard", "Stone", "Sword", "Tomb", "Tower", "Vow",
    "Wanderer", "Watcher", "Wizard", "Wood",
  ],

  names: {
    male: [
      "Aerin", "Aldwin", "Bran", "Cael", "Daeron", "Edric",
      "Eowin", "Faramir", "Gareth", "Halric", "Ivar", "Jorund",
      "Kael", "Lannis", "Maric", "Nessar", "Orin", "Perrin",
      "Quill", "Rorik", "Sael", "Toren", "Ulric", "Varin",
      "Wendell", "Xanthor", "Yorvik", "Zarath", "Bryn", "Corwin",
    ],
    female: [
      "Aelin", "Brynn", "Cailen", "Daera", "Elowyn", "Fenna",
      "Gwen", "Halia", "Imogen", "Jora", "Kira", "Lyra",
      "Maela", "Nyssa", "Oriane", "Perynn", "Quenna", "Riala",
      "Saera", "Tessa", "Una", "Vesna", "Wren", "Xoria",
      "Yenna", "Zara", "Aevril", "Brenna", "Caelyn", "Dalia",
    ],
    neutral: [
      "Arven", "Brae", "Cedric", "Devin", "Erilen", "Fae",
      "Galen", "Hael", "Ilien", "Joren", "Kael", "Linnen",
      "Marin", "Naev", "Olen", "Pell", "Quen", "Rael",
      "Saen", "Tael", "Ull", "Vel", "Wyn", "Xael",
      "Yren", "Zhael", "Aeris", "Bren", "Caor", "Dyn",
    ],
  },

  locations: [
    "An old stone bridge, half-collapsed",
    "A tavern with too few patrons and a watchful host",
    "A high mountain pass under threatening sky",
    "A crypt freshly disturbed",
    "A merchant caravan halted in suspicion",
    "A forest of pale trees, no birdsong",
    "A king's court between sessions",
    "A wizard's tower, lights still burning",
    "A village green at festival",
    "A river ford guarded by armoured strangers",
    "A roadside shrine left tended",
    "An abandoned watchtower atop a hill",
    "A monastery with a sealed inner gate",
    "A dwarven hall ringing with hammers",
    "An elven glade silvered by moonlight",
    "A battlefield three days cold",
    "A walled city's outer market at dusk",
    "A crossroads where four signposts disagree",
    "A keep under siege by an unseen enemy",
    "A shipwreck breaking up on rocks",
    "A sacked manor house, smoke still rising",
    "A guildhall cellar piled with crates",
    "A dragon's hoard, its owner absent",
    "A buried temple, only a doorway visible",
    "A meadhall where the doors have been barred",
    "A thieves' den behind a butcher's shop",
    "A lake with no fish, no reeds, perfect stillness",
    "A pass through bone-dry mountains",
    "A herbalist's cottage emptied in a hurry",
    "A standing stone circle on a barren moor",
    "A library where books have been burned in piles",
    "A ducal hunting lodge, shutters closed",
    "A fortified inn at the edge of the wild",
    "A sea cave hung with strange weed",
    "A mine tunnel where the lamps refuse to light",
    "An orchard fruit-laden but unworked",
    "A drovers' road dotted with milestones",
    "A leper's hospital just outside town walls",
    "A pirate cove sheltered by sea cliffs",
    "A high pass between two rival kingdoms",
  ],

  catalysts: [
    "An old debt is called in publicly",
    "A messenger arrives with news of a death",
    "A relic thought lost is suddenly seen",
    "A friend asks for shelter — and is being followed",
    "An oath is broken in front of witnesses",
    "A child goes missing under the moon",
    "A stranger claims the hero's name",
    "The crown summons by name and title",
    "A banner thought destroyed flies again",
    "A sword breaks at exactly the wrong moment",
    "Wolves answer a horn no one blew",
    "A dragon is rumoured returned",
    "A long-dead king is seen on a road",
    "A village offers tribute to a hidden master",
    "A noble proposes marriage as a trap",
    "A prophecy is read aloud and named",
    "An exiled brother appears, wounded",
    "The harvest fails for the third year",
    "A holy place is found defiled",
    "A traveling priest demands sanctuary",
    "Bandits under unfamiliar colours raid the hold",
    "A knight challenges to single combat",
    "A spell-bound oath compels obedience",
    "An old enemy offers an unexpected truce",
    "A map is pressed into the hero's hand by a dying scout",
    "Rumours spread of a chosen one — falsely named",
    "The local lord is replaced overnight",
    "A relic shatters when touched",
    "A captive begs for mercy in a foreign tongue",
    "The sea gives up an unburied body",
    "A festival is interrupted by armoured riders",
    "A signal fire burns where none was lit",
    "A trusted ally vanishes between watches",
    "A library opens to an unknown book",
    "A wedding is interrupted by an old vow",
    "A ghost demands what was promised",
    "A foreign envoy arrives with offerings and lies",
    "An augur reads omens that contradict",
    "A storm holds the road for three days too many",
    "A cult thought stamped out is found at the heart of a city",
    "A coin is pressed into the hero's hand — minted by a dead crown",
    "A thief returns what they stole and asks forgiveness",
    "A knight takes the wrong side and asks for help to undo it",
    "Children sing a song no parent taught them",
    "A bell tolls in a tower with no bell",
    "An ally is revealed to wear two crests",
    "A binding written in ash flares back to colour",
    "A sword refuses its sheath",
    "A sworn brother breaks faith without explanation",
    "A king dies; the heir is missing",
  ],

  sensory: {
    hear: [
      "Distant horns answering each other",
      "A creak of leather and chainmail",
      "A bell tolling slowly, no clear source",
      "The whisper of wind in dry leaves",
      "A child laughing somewhere unseen",
      "A blade being drawn in another room",
      "Hooves on cobblestone fading north",
      "Crows arguing in a high wood",
      "Hammer on anvil, deep below",
      "A song in an old tongue, half-remembered",
      "Boots on stone in a measured tread",
      "Water dripping into hollow stone",
      "Wolves at a long distance",
      "A door scraping open against grit",
      "The hush of falling snow",
      "A horse breathing hard in shadow",
      "Murmured prayer behind a curtain",
      "Wood splintering under weight",
      "A flag snapping in cold wind",
      "The clink of coin counted twice",
      "Steel kissing steel in practice",
      "Rain on a thatched roof",
      "Owls calling across a marsh",
      "Footsteps quickening behind, then stopping",
    ],
    see: [
      "A line of torches winding up a hill",
      "A shape in the mist that does not move",
      "Smoke rising from a settlement that should not have fires",
      "Leaves rotating slowly in still water",
      "Banners hung upside down in mourning",
      "A figure crossing the road and not coming out the other side",
      "Stars unfamiliar above a familiar wood",
      "Blood drying in a careful pattern",
      "A scrap of cloth caught on a thorn — embroidered",
      "Tracks coming in but not going out",
      "A door ajar that should have been barred",
      "Dust motes lit by a single lance of sun",
      "The flicker of armour through a treeline",
      "A child watching from a high window",
      "A horse standing untethered in a clearing",
      "Crows circling something out of sight",
      "Silver thread caught in moonlight",
      "Two campfires too close to be allies",
      "Footprints filled with rainwater, fresh",
      "A statue's face newly chipped",
      "A flame steady where there is no draft",
      "An animal eye in the firelight, low to the ground",
      "A standing stone leaning that wasn't",
      "Pages torn from a book and pinned to a tree",
    ],
    feel: [
      "A draft from a place where no draft should be",
      "Cold settling between the shoulder blades",
      "A pricking on the back of the neck",
      "The weight of a stone in the palm",
      "Damp wool against the skin",
      "Smooth iron warmer than it should be",
      "Wood beneath the boots giving slightly",
      "A heartbeat too quick to slow",
      "The steady press of a sword belt at the hip",
      "Heat from a forge through a closed door",
      "Hair lifting before lightning",
      "Rope scrape across a callused palm",
      "Mud sucking at boots, slowing the stride",
      "The soft give of moss over stone",
      "A breath held instinctively",
      "Sweat drying on the small of the back",
      "Ground vibrating with distant feet",
      "Saddle leather warming under the body",
      "A faint tremor in fingers gripping a hilt",
      "Cold metal pressed into the hand by a stranger",
      "Snow stinging the cheeks",
      "A weight removed when something agrees to leave",
      "Sand sliding underfoot on a worn step",
      "The tug of cloth caught on a corner",
    ],
    smell: [
      "Woodsmoke and damp wool",
      "Iron and old blood",
      "Pine sap warming in sun",
      "Stale beer and floor-rushes",
      "Tallow candles guttering",
      "Wet stone and mineral cold",
      "Frankincense and old prayer",
      "Horse sweat and saddle oil",
      "Bread baking somewhere out of sight",
      "Pitch and tar from a harbour",
      "Old leather and parchment",
      "Cured ham hung in rafters",
      "Mead spilled across rushes",
      "Sea salt and rope",
      "Damp earth turned by rain",
      "Burned thatch, hours old",
      "Pine and spruce in a clean wind",
      "Spices from a far market",
      "Mildewed cloth in an unaired chest",
      "Lamp oil and ink",
      "A forge nearby, hot iron",
      "Cold water from a stone trough",
      "Moss and rot, just past the path",
      "Horses, hay, and the warm dark of a stable",
    ],
  },
};
