/* Universal-Oracle / rpg / packs / age-of-sail.js
   17th-19th century nautical — frigates and merchantmen, doubloons and press
   gangs, salt and tar and broken oaths in port. Original genre flavour;
   no card content reproduced from any commercial deck. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS["age-of-sail"] = {
  name: "Age of Sail",
  tone: "Salt, tar, and a long memory at the wharf.",

  verbs: [
    "Anchor", "Bargain", "Becalm", "Board", "Bribe", "Capsize",
    "Careen", "Chart", "Coil", "Commission", "Consign", "Cruise",
    "Discover", "Dispatch", "Drift", "Duel", "Embark", "Engage",
    "Escape", "Flag", "Flee", "Furl", "Hail", "Haul",
    "Hazard", "Heave to", "Heel", "Hold course", "Hunt", "Impress",
    "Intercept", "Lay alongside", "Make sail", "Maroon", "Mutiny", "Negotiate",
    "Patrol", "Press", "Pursue", "Ransom", "Reef", "Repair",
    "Salute", "Salvage", "Scuttle", "Search", "Sight", "Signal",
    "Sink", "Slip moorings", "Smuggle", "Spy", "Stow", "Strike colours",
    "Tack", "Tow", "Trade", "Trim", "Veer", "Watch",
    "Weigh anchor",
  ],

  adjectives: [
    "Adrift", "Becalmed", "Bilge-stained", "Black-flagged", "Boarded", "Brackish",
    "Cargo-laden", "Caulked", "Coast-hugging", "Convoyed", "Damp", "Dry-docked",
    "Embargoed", "Far-flung", "Foreign", "Foundering", "Hardtack-stale", "Hazy",
    "Hidden", "Iron-bound", "Letter-marqued", "Listing", "Long-hauled", "Mast-bare",
    "Merchantman", "Misty", "Mutinous", "Naval", "Open-decked", "Out-bound",
    "Overpowered", "Overtaken", "Pirate-flagged", "Plundered", "Provisioned", "Press-ganged",
    "Reef-rocked", "Rigged", "Rope-burned", "Rum-soaked", "Salt-crusted", "Sea-battered",
    "Sea-stained", "Shallow-drafted", "Sloop-rigged", "Smuggled", "Sneaking", "Storm-tossed",
    "Tar-stained", "Trade-bound", "Treasure-laden", "Wave-broken", "Weather-beaten", "Weather-bound",
    "Wind-locked", "Wind-stilled", "Yardarm-deep",
  ],

  nouns: [
    "Admiral", "Anchor", "Anchorage", "Barometer", "Bilge", "Boatswain",
    "Bowsprit", "Brig", "Cabin", "Cabin boy", "Cannon", "Cape",
    "Captain", "Capstan", "Cargo hold", "Carpenter", "Chart", "Chart house",
    "Coast", "Commission", "Commodore", "Compass", "Convict", "Cooper",
    "Cordage", "Corsair", "Crow's nest", "Cutter", "Deck", "Dirk",
    "Dispatch", "Doubloon", "Dockmaster", "East Indiaman", "Estuary", "Excise",
    "Flag", "Fleet", "Flotilla", "Forecastle", "Frigate", "Galleon",
    "Galley", "Gangway", "Gold", "Gunner", "Gunwale", "Halyard",
    "Hammock", "Harbor", "Harbormaster", "Hawser", "Helmsman", "Hold",
    "Hull", "Inlet", "Jolly Roger", "Knot", "Lantern", "Latitude",
    "Letter of marque", "Lieutenant", "Lifeboat", "Lighthouse", "Logbook", "Longitude",
    "Lookout", "Mainmast", "Map", "Marines", "Mate", "Merchant",
    "Midshipman", "Mizzen", "Mutineer", "Navigator", "Octant", "Parley",
    "Passage", "Pendant", "Pirate", "Plank", "Port", "Powder",
    "Press gang", "Privateer", "Prize", "Purser", "Quartermaster", "Quayside",
    "Rigging", "Royal Navy", "Rudder", "Rum", "Sail", "Sailor",
    "Schooner", "Scrimshaw", "Seabird", "Sextant", "Ship", "Ship's biscuit",
    "Sloop", "Smuggler", "Stevedore", "Surgeon", "Tar", "Telescope",
    "Tide", "Tiller", "Topsail", "Trade", "Treasure", "Treaty",
    "Voyage", "Wake", "Watch", "Wharf", "Wheel", "Wind",
    "Wreck", "Yardarm",
  ],

  names: {
    male: [
      "Anders", "Beauregard", "Carlos", "Dimitri", "Eduardo", "Finn",
      "Gareth", "Hadji", "Ibrahim", "Jacques", "Kostas", "Liam",
      "Marcos", "Nikolas", "Olaf", "Pedro", "Quintin", "Rashid",
      "Soren", "Theo", "Umar", "Vasco", "Wilbur", "Yusuf",
    ],
    female: [
      "Adelina", "Beatrice", "Catalina", "Despina", "Esme", "Fatima",
      "Genevieve", "Henriette", "Inara", "Jeanette", "Khadija", "Lucia",
      "Mireille", "Nadia", "Ophelia", "Penelope", "Quinta", "Rosalind",
      "Sofia", "Talitha", "Uma", "Vedette", "Winifred", "Zara",
    ],
    neutral: [
      "Ash", "Brae", "Cale", "Drift", "Ember", "Finch",
      "Gale", "Hale", "Iris", "Joss", "Kestrel", "Lark",
      "Mer", "Nev", "Orin", "Pell", "Quill", "Ren",
      "Salt", "Tide", "Vale", "Wren", "Yale", "Zale",
    ],
  },

  locations: [
    "A dockside tavern with the captain's pipe still warm",
    "A lighthouse keeper's cottage with one window unlit",
    "A naval shipyard at low tide",
    "A merchant frigate's hold during inspection",
    "A privateer's anchorage hidden by mangroves",
    "A customs office staffed by one weary clerk",
    "A press gang's table outside a chapel",
    "A pirate cove with a wreck visible at low water",
    "A quayside market trading three currencies",
    "A galley below decks just before bell",
    "A captain's cabin with the chart pinned by daggers",
    "A foredeck during a sermon at sea",
    "A brig where the prisoner has been singing for two days",
    "A schooner's deck during a thunder squall",
    "A chandlery overstocked with one type of rope",
    "A magistrate's court in a port colony",
    "A ship's surgeon's parlour over a tavern",
    "A merchant's counting-house with foreign clerks",
    "A fishing village at the wrong tide",
    "A flagship's wardroom mid-meeting",
    "A naval drydock with a hull half-stripped",
    "A gallows pier at sunrise",
    "A shipwright's loft full of half-models",
    "A widow's walk with the lamp lit at noon",
    "A crow's nest with the lookout asleep",
    "A monastery on an island that levies no tithe",
    "A trading post run by ex-pirates",
    "A botanical garden funded by smuggler money",
    "A diplomat's drawing-room in a treaty port",
    "A wreck-rich shoal with the bell still ringing",
    "A naval academy's quadrangle the day before exams",
  ],

  catalysts: [
    "A press gang knocks at the inn at dawn",
    "A treasure map turns up signed in three different hands",
    "A captain's commission lapses without explanation",
    "A letter of marque is found bound into a hymnal",
    "The compass swings five points and won't return",
    "A widow's pension is paid in foreign coin",
    "A becalmed sea fills with strange birds",
    "A sailor returns reportedly drowned",
    "A French frigate hails under English colours",
    "A surgeon's mate is found writing in code",
    "A bishop in port quietly issues passage papers",
    "A merchant's manifest doesn't match the cargo on the dock",
    "A storm holds the fleet in port for a week the season can't spare",
    "A ship boy delivers a sealed letter and disappears",
    "A pirate captain offers a parley under truce",
    "A naval inspector arrives with a list of names",
    "A ship's bell tolls once with no hand near it",
    "A commissary embezzles in a way that benefits the captain",
    "A treasure cache is rumoured a day's sail off-route",
    "An old shipmate calls in a debt at the worst time",
    "A diplomat's wife asks for unscheduled passage",
    "A noble offers a private commission outside the navy",
    "A mate breaks ranks during a watch",
    "A watchman is found senseless in a locked stateroom",
    "A signal fire burns where there should be no shore",
    "Trade winds shift two weeks early",
    "A foreign court issues a recall on a vessel mid-passage",
    "A charted island isn't there",
    "A prize is taken from another captain's wake",
    "A drowned man's effects include the wrong commission",
  ],

  sensory: {
    hear: [
      "Rigging creaking through a turn",
      "A bosun's pipe between watches",
      "Holy-stones grinding teak at dawn",
      "Cannon ports being run out two decks below",
      "A choir of seabirds following the wake",
      "A bell tolling between knots",
      "Voices carrying further over still water than expected",
      "A canvas snapping as it takes wind",
      "Coins counted on a wooden table",
      "Boot-heels on a quarterdeck",
      "A surgeon's saw, briefly",
      "A captain's spyglass shutting",
      "A ship's cat purring near the helm",
      "A foreign sailor's chant from the foc'sle",
      "Swells slapping the hull like a slow drum",
      "A cabin door latched twice, hard",
    ],
    see: [
      "A flag run up that isn't the one expected",
      "Tar weeping from a deck plank",
      "A crow's nest empty during a watch",
      "A wake that bends to one side",
      "A bird that lands on the rigging and stays",
      "A shore that doesn't match the chart",
      "Two sets of footprints in the morning dew on deck",
      "A kettle's smoke straight up in port",
      "A sealed bottle floating against the current",
      "A captain's coat hung but the cabin empty",
      "A clerk crossing out one name and adding another",
      "A figurehead's eyes painted over",
      "A sail patched with foreign canvas",
      "A pier post with three crowns burned in",
      "A widow on the quay in mourning before the news",
      "A sextant box already opened, contents wrong",
    ],
    feel: [
      "A deck slick with morning dew and tar",
      "A pipe stem warm from a stranger's hand",
      "Salt drying on a forearm",
      "Iron of a cannonball through a glove",
      "Rope rasp through a callused palm",
      "A coin too cold for one in a warm pocket",
      "Pitch sticky on a bare foot",
      "Spray finding the same spot on a cheek",
      "Lantern oil on the back of a hand",
      "A drift below decks that shouldn't be",
      "A capstan creaking under your weight",
      "Wool wet through a peacoat",
      "A sealed chest's heaviness in the wrong direction",
      "Powder grit between teeth",
      "Brass of a sextant warming to morning sun",
      "A signed letter pressed into a palm at the wharf",
    ],
    smell: [
      "Tar and hemp in the rigging",
      "Salt and gunpowder after a drill",
      "Rum freshly broached",
      "Pipe-tobacco from a wardroom door",
      "Salt-pork cooking below decks",
      "Wet wool and lamp oil",
      "Pitch warmed by sun",
      "Spices from a hold opened after months at sea",
      "Brackish water against a green hull",
      "Cordite in a closed gun deck",
      "Iodine and ship's biscuit",
      "Beeswax from a freshly-polished captain's table",
      "Foreign perfume on a sea-letter",
      "Hot brass from a freshly-fired carronade",
      "Coffee from the wardroom at watch change",
      "Sailcloth and pine pitch",
    ],
  },

  belongings: [
    { category: "Naval kit",         items: ["bosun's whistle", "rope splice", "knife on a lanyard"] },
    { category: "Trade goods",       items: ["packet of foreign tea", "spice paper", "small silver bar"] },
    { category: "Charts & papers",   items: ["sea chart corner", "letter of marque", "ship's manifest"] },
    { category: "Pocket change",     items: ["clipped silver", "paper notes", "a handful of pence"] },
    { category: "Sailor's tools",    items: ["fid", "sailmaker's needle", "tar-stained palm"] },
    { category: "Concealed weapons", items: ["pocket pistol", "boot-knife", "blackjack"] },
    { category: "Hold goods",        items: ["dried apples", "tea cake", "small jar of rum"] },
    { category: "Officer's effects", items: ["sealing wax", "signet ring", "captain's pipe"] },
  ],
};
