/* Universal-Oracle / rpg / packs / postapoc.js
   Post-apocalyptic. Tone: scarcity, rust, distrust, the long quiet after. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS.postapoc = {
  name: "Post-Apocalyptic",
  tone: "Scarcity, rust, distrust — what survives, what doesn't.",

  verbs: [
    "Abandon", "Ambush", "Barter", "Bleed", "Bolt", "Bury",
    "Cache", "Conserve", "Contaminate", "Crawl", "Defend", "Deny",
    "Dig", "Drag", "Drown", "Endure", "Escape", "Forage",
    "Fortify", "Hide", "Hoard", "Hunt", "Improvise", "Infect",
    "Mend", "Mourn", "Patch", "Plead", "Plunder", "Poison",
    "Promise", "Protect", "Quarantine", "Ration", "Refuse", "Repair",
    "Retreat", "Reveal", "Salvage", "Scavenge", "Shelter", "Signal",
    "Smuggle", "Starve", "Survive", "Trade", "Trail", "Trespass",
    "Trust", "Unearth", "Wander", "Warn",
  ],

  adjectives: [
    "Abandoned", "Ash-choked", "Bleached", "Broken", "Buried", "Burnt",
    "Charred", "Choked", "Contaminated", "Cracked", "Crumbling", "Desperate",
    "Dry", "Empty", "Feral", "Filthy", "Frayed", "Gaunt",
    "Greasy", "Hollow", "Hungry", "Improvised", "Jagged", "Looted",
    "Lost", "Makeshift", "Patchwork", "Poisoned", "Quiet", "Radiated",
    "Rationed", "Ravaged", "Rotting", "Rusted", "Salvaged", "Scarred",
    "Scavenged", "Shaken", "Silent", "Stained", "Starving", "Sun-bleached",
    "Tattered", "Toxic", "Trembling", "Twisted", "Watchful", "Weather-worn",
    "Weeping", "Withered", "Wretched", "Yellowed",
  ],

  nouns: [
    "Ammunition", "Antibiotics", "Ashes", "Bandage", "Barricade", "Bunker",
    "Canister", "Caravan", "Cellar", "Chain", "Convoy", "Crater",
    "Deal", "Drum", "Dust", "Engine", "Fence", "Fever",
    "Filter", "Generator", "Geiger count", "Goods", "Grain", "Hideout",
    "Hose", "Hostage", "Knife", "Lantern", "Lockup", "Map",
    "Mask", "Medic", "Neighbor", "Outpost", "Patch", "Pipeline",
    "Promise", "Pump", "Radio", "Ration", "Rumour", "Salvage",
    "Scout", "Settlement", "Signal", "Skin", "Smoke", "Spare",
    "Stash", "Survivor", "Tank", "Toll", "Trade", "Vault",
    "Warning", "Watchtower", "Water", "Wire", "Wound",
  ],

  names: {
    male: [
      "Asher", "Bram", "Cole", "Dax", "Echo", "Finch",
      "Gus", "Hale", "Ike", "Jace", "Knox", "Lev",
      "Mace", "Nix", "Owen", "Pike", "Quinn", "Rook",
      "Sax", "Tate", "Uri", "Vance", "Wyatt", "Zane",
    ],
    female: [
      "Ada", "Briar", "Caro", "Dax", "Eve", "Faye",
      "Gia", "Hale", "Iris", "Jen", "Kit", "Lana",
      "Maud", "Nell", "Otis", "Penn", "Quinn", "Reva",
      "Sasha", "Tilda", "Uma", "Vesta", "Wren", "Zora",
    ],
    neutral: [
      "Ash", "Blue", "Crow", "Dust", "Echo", "Fox",
      "Grey", "Hale", "Ink", "Joss", "Kit", "Loam",
      "Mar", "Nox", "Onyx", "Pip", "Quill", "Rust",
      "Sage", "Tin", "Vex", "Wisp",
    ],
  },

  locations: [
    "A gas station picked clean — except for one locked drawer",
    "An overpass camp with watch fires both ends",
    "A drained reservoir with vehicles half-buried in mud",
    "A library that's been turned into a fortress",
    "A grocery store stripped to the rebar",
    "A radio mast still humming, somehow",
    "A train tunnel that drips and echoes",
    "A motel sign rusted past reading",
    "A ranch house with the doors nailed shut from inside",
    "A scrapyard ruled by a single old man and three dogs",
    "A church basement converted into a clinic",
    "A school converted into a settlement, kids on the roof",
    "A desert highway with abandoned cars every half-mile",
    "A water-treatment plant guarded by a hostile crew",
    "A drive-in cinema turned trade ground",
    "A flooded subway station ringing with distant footsteps",
    "A shopping mall cleared of everything but the floor tile",
    "A high-rise that survived but is empty above the third floor",
    "A bridge demolished at one end, used as a checkpoint",
    "A logging camp with too few people for the gear they have",
    "A wind farm with a single tower still turning",
    "A hospital wing sealed off behind plastic sheeting",
    "A stranded freight train, doors welded",
    "A farmhouse with a perfect garden in a dead landscape",
    "A drainage culvert big enough to live in",
    "A roadside shrine made from rebar and welded names",
    "A municipal pool drained, stockpiled with crates",
    "A radio station broadcasting on loop with no announcer",
    "A bombed-out airport with one usable runway",
    "A trading post at a dry river crossing",
    "A bunker entrance with old paint over a faded biohazard mark",
    "A coastal lighthouse repurposed as a watchpoint",
    "A salvage yard where dogs bark from inside a wreck",
  ],

  catalysts: [
    "The water filter fails without warning",
    "A stranger walks in carrying real medicine",
    "Raiders hit the next settlement over and someone escapes here",
    "An old comm channel comes alive with a familiar voice",
    "A child shows symptoms no one wants to name",
    "Fuel runs lower than the route allows",
    "A trusted partner is caught hiding contraband",
    "A pre-collapse map is found pointing to here",
    "A truck convoy is heard on the road, direction unclear",
    "A long-quiet siren starts at sundown",
    "A scout returns alone, missing equipment",
    "A neighbour offers a deal that's too good",
    "Dogs alert to something approaching downwind",
    "A radio broadcast names individuals by name",
    "Someone is found dead with a stamped warning on their chest",
    "A storm front moves in faster than forecast — and the air tastes wrong",
    "An old enemy arrives unarmed, asking",
    "A child claims to remember the old world clearly",
    "An informant reveals a price has been put on a head",
    "The watchtower goes silent on the night shift",
    "A package is left at the perimeter, contents unknown",
    "Grain from the cache is found mouldy underneath",
    "A drone is heard circling, low and slow",
    "A long-time member asks to leave, with reasons",
    "A printed photo is left where it must be found",
    "A fence section is cut clean — by someone who knew the schedule",
    "Migrant survivors arrive demanding entry",
    "An old boss-figure returns with stories that don't add up",
    "A cure is rumoured one valley over",
    "Geiger counters spike in a place that always read clean",
    "A messenger collapses inside the wire, half-dead",
    "Trades are refused that have never been refused before",
    "A lock is found broken from the inside",
    "Strangers are using your call signs",
    "A prophecy from a wandering preacher names dates",
  ],

  sensory: {
    hear: [
      "Wind through bent rebar",
      "A generator chugging, missing every fourth beat",
      "The wet click of a Geiger counter rising",
      "Distant gunfire, three rounds, then nothing",
      "A radio carrier wave with no voice",
      "Crows on metal, scraping",
      "Boots on broken glass, deliberate",
      "A dog whining, low and steady",
      "A child coughing in the next room",
      "A truck engine turning over, failing, turning over",
      "Plastic sheeting rattling in wind",
      "Far-off thunder that doesn't seem like weather",
      "The hum of fluorescent tubes too long left on",
      "Water dripping into a metal drum",
      "Static where a station used to be",
      "Helicopter blades, distance unclear",
    ],
    see: [
      "A column of black smoke on the horizon",
      "Tally marks on a doorframe, recent",
      "A rusted car still locked, contents intact",
      "Birds that have stopped flying south",
      "A figure on a ridge, unmoving for too long",
      "Faded paint over older paint over a brand name",
      "A meal half-eaten on a kitchen counter",
      "Dust pattern showing something was just removed",
      "A green growth where nothing should grow",
      "A child's drawing pinned to a checkpoint board",
      "Empty shelves with one item left, untaken",
      "Tire tracks crossing tracks that didn't",
      "A line of clothing on a fence, faded by sun",
      "An animal carcass with no scavenger marks",
      "Wire stretched between trees, eye-height",
      "A mirror nailed up on an outside wall",
    ],
    feel: [
      "Grit in the teeth that won't rinse away",
      "Sun heat through fabric, making sweat run cold",
      "A sudden draft from a place that shouldn't have one",
      "The weight of a full water bottle, then less",
      "Rust flaking off a railing onto the palm",
      "Cold concrete through a sleeping bag",
      "Adrenaline-shake in the hands well after danger",
      "Dry lips cracking when you smile",
      "Pressure in the ears as wind shifts",
      "A small piece of glass under a sock",
      "Fabric stiff with old sweat",
      "An itch under bandages that shouldn't itch yet",
      "A weapon's grip warming to the hand",
      "Plastic snap of a respirator seating right",
      "Engine vibration through the floor of a vehicle",
      "Cold metal of a key passed in a handshake",
    ],
    smell: [
      "Diesel and old smoke",
      "Rust and rainwater",
      "Antiseptic and copper",
      "Sun-baked plastic",
      "Mildew under floorboards",
      "Cordite in a closed room",
      "Old meat going wrong slowly",
      "Wet dog and woodsmoke",
      "Burnt wiring",
      "Stale coffee held too long",
      "Oil and motor heat",
      "Latex gloves and bleach",
      "Powdered milk reconstituted",
      "Dust raised by something heavy passing",
      "Aerosol propellant",
      "A stranger's jacket — sweat, fuel, cigarettes",
    ],
  },

  belongings: [
    { category: "Salvage",            items: ["scrap metal", "tangled wires", "a broken radio"] },
    { category: "Survival kit",       items: ["water filter", "bandages", "ration bar"] },
    { category: "Trade goods",        items: ["cigarettes", "batteries", "a bottle of antibiotics"] },
    { category: "Tools",              items: ["roll of duct tape", "multitool", "flashlight"] },
    { category: "Improvised weapons", items: ["lead pipe", "sharpened screwdriver", "makeshift gun"] },
    { category: "Personal mementos",  items: ["faded photo", "folded letter", "wedding ring"] },
    { category: "Ammunition",         items: ["shotgun shells", "a magazine", "loose brass casings"] },
    { category: "Medicine",           items: ["pill bottles", "antiseptic", "syringes"] },
  ],
};
