/* Universal-Oracle / rpg / packs / scifi.js
   Science Fiction. Tone: starships and treaties, deep time, the long quiet of vacuum. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS.scifi = {
  name: "Science Fiction",
  tone: "Starships and treaties, deep time, the long quiet of vacuum.",

  verbs: [
    "Acquire", "Authorise", "Bargain", "Boost", "Brief", "Calibrate",
    "Chart", "Clear", "Code", "Confer", "Connect", "Contract",
    "Court-martial", "Decommission", "Decompress", "Decrypt", "Defect", "Detect",
    "Dispatch", "Disrupt", "Drift", "Engage", "Erase", "Escape",
    "Establish", "Evacuate", "Exchange", "Extract", "Fly cover", "Forge",
    "Hail", "Hijack", "Inject", "Inspect", "Intercept", "Interrogate",
    "Investigate", "Jump", "Land", "Launch", "Liberate", "Liquidate",
    "Map", "Mediate", "Mine", "Negotiate", "Network", "Observe",
    "Override", "Patch", "Patrol", "Pilot", "Plot", "Probe",
    "Promote", "Pursue", "Quarantine", "Recall", "Recover", "Redirect",
    "Reduce", "Reinforce", "Relay", "Render", "Report", "Resolve",
    "Retrieve", "Reveal", "Salvage", "Scan", "Seal", "Seize",
    "Settle", "Sign on", "Smuggle", "Stabilise", "Strike", "Surrender",
    "Survey", "Track", "Translate", "Transport", "Treat", "Trespass",
    "Unmask", "Vaccinate", "Verify", "Warp", "Wake",
  ],

  adjectives: [
    "Abandoned", "Accelerated", "Adrift", "Alien", "Alloyed", "Anomalous",
    "Authoritative", "Backwater", "Bonded", "Calibrated", "Catalytic", "Charted",
    "Chrome", "Civilian", "Classified", "Coded", "Cold-sleep", "Colonial",
    "Compromised", "Contested", "Cracked", "Critical", "Cryogenic", "Cybernetic",
    "Decommissioned", "Decompressed", "Delegated", "Detected", "Diplomatic", "Disabled",
    "Distress-flagged", "Encoded", "Endangered", "Engaged", "Engineered", "Evacuated",
    "Federated", "Filtered", "Flagged", "Forensic", "Frontier", "Glassy",
    "Gravitational", "Hailed", "Hardened", "Hostile", "Hyperluminal", "Ice-locked",
    "Indentured", "Inertial", "Insurgent", "Intercepted", "Irradiated", "Junked",
    "Junker-class", "Live-fire", "Logged", "Lost-contact", "Mercenary", "Microgravity",
    "Militarised", "Mil-grade", "Modified", "Monitored", "Networked", "Neutron-shielded",
    "Off-world", "Open-channel", "Orbital", "Outpost", "Pirate", "Plotted",
    "Probationary", "Prototype", "Quarantined", "Rated", "Re-flagged", "Rendered",
    "Retired", "Revoked", "Rigged", "Routed", "Sanctioned", "Scarred",
    "Sealed", "Settled", "Shielded", "Slip-jumped", "Smuggler-flagged", "Stable",
    "Surveyed", "Threatened", "Tracked", "Transferred", "Treaty-bound", "Unbonded",
    "Uncharted", "Unlogged", "Vacuum-rated", "Verified", "Warp-capable", "Worn",
  ],

  nouns: [
    "Admiralty", "Ambassador", "Asteroid", "Atmosphere", "Authority", "Beacon",
    "Berth", "Biosphere", "Bond", "Boost", "Boarding party", "Bounty",
    "Briefing", "Bulkhead", "Cargo", "Carrier", "Cell", "Channel",
    "Chart", "Citizenship", "Civilian", "Clearance", "Cloning facility", "Code",
    "Colonist", "Colony", "Comm relay", "Compact", "Concession", "Conduit",
    "Conscript", "Contract", "Convoy", "Coordinates", "Core", "Corporation",
    "Council", "Courier", "Court martial", "Crewman", "Cryopod", "Custodial",
    "Cypher", "Database", "Debris", "Deck", "Defector", "Delegation",
    "Diplomat", "Dispatch", "Distress call", "Dock", "Dome", "Drone",
    "Drop pod", "Edict", "Embassy", "Encryption", "Engineer", "Envoy",
    "Escort", "Exchange", "Exoplanet", "Expedition", "Expat", "Extraction",
    "Fabricator", "Fleet", "Forge", "Frontier", "Fuel cell", "Gate",
    "Generation ship", "Genome", "Geyser", "Gradient", "Grav plate", "Guild",
    "Habitat", "Hacker", "Hatch", "Heat sink", "Helm", "Holdfast",
    "Holo", "Homestead", "Hull", "Hyperdrive", "Ice", "Identity chip",
    "Indenture", "Insurgent", "Intelligence", "Investigator", "Jump", "Jurisdiction",
    "Lifesupport", "Magazine", "Manifest", "Marines", "Marshal", "Medic",
    "Memory core", "Mercenary", "Message buoy", "Microgravity", "Militia", "Mineral rights",
    "Mission", "Module", "Moon", "Negotiation", "Network", "Nomad",
    "Observatory", "Officer", "Operative", "Orbit", "Outpost", "Override",
    "Pact", "Patrol", "Pilot", "Pirate", "Pit boss", "Plant",
    "Plasma", "Polity", "Probe", "Prosthetic", "Prospector", "Quarantine",
    "Quartermaster", "Reactor", "Refugee", "Registry", "Relay", "Report",
    "Rescue", "Reserve", "Rig", "Rim", "Sabotage", "Salvage",
    "Sanctions", "Scout", "Sealed locker", "Section", "Sensor", "Settlement",
    "Shipboard", "Shore leave", "Shuttle", "Signal", "Sleeper", "Slipstream",
    "Smuggler", "Solar", "Spacedock", "Spy", "Squadron", "Standard",
    "Star map", "Station", "Strike team", "Subspace", "Suit", "Surveyor",
    "Survivor", "Syndicate", "Talent", "Tariff", "Tax-haven", "Telemetry",
    "Tender", "Terraformer", "Threshold", "Throughway", "Tractor beam", "Transponder",
    "Treaty", "Trustee", "Tunnel", "Underdeck", "Uplink", "Veteran",
    "Visa", "Voyage", "Warp", "Watchstation", "Wreck",
  ],

  names: {
    male: [
      "Adan", "Boaz", "Cyril", "Dmitri", "Erran", "Faolan",
      "Garrick", "Hadrian", "Ito", "Jules", "Kael", "Lukas",
      "Marik", "Nestor", "Osric", "Petar", "Quill", "Ravi",
      "Sergei", "Tycho", "Ulysses", "Vincente", "Wren", "Zane",
    ],
    female: [
      "Anya", "Brigid", "Catra", "Diona", "Elena", "Freya",
      "Galina", "Halia", "Imara", "Junia", "Kira", "Liesl",
      "Mira", "Nadia", "Octavia", "Petra", "Quinn", "Rhea",
      "Sasha", "Tamsin", "Una", "Vesna", "Wei", "Zara",
    ],
    neutral: [
      "Arc", "Bracken", "Caer", "Drift", "Echo", "Frey",
      "Gale", "Hale", "Ion", "Jova", "Kai", "Linnen",
      "Mar", "Nyx", "Onyx", "Pell", "Quark", "Rook",
      "Solas", "Tev", "Umber", "Vale", "Wren", "Zephyr",
    ],
  },

  locations: [
    "A station's promenade between shifts",
    "A cargo hold with one container leaking heat",
    "A frontier outpost with a dish that's been re-aligned recently",
    "A diplomatic lounge on a station of two flags",
    "A wrecked freighter still under power",
    "A maintenance crawlway hot with leaking coolant",
    "A passenger berth with no passengers, ticketed",
    "A planetary refugee camp at orbital lift",
    "A docking ring with one slot under quarantine",
    "A bridge during a hand-over of command",
    "An asteroid hollowed for habitation, only one airlock open",
    "A cantina off the cargo deck of a generation ship",
    "A relay station with a backlog of unsent messages",
    "A research dome on an unsurveyed world",
    "A hyperjump way-point with overlapping court orders",
    "A scrap yard rumoured to keep one ship still flightworthy",
    "An embassy reception with security in non-uniform",
    "A reactor room with one panel out of commission",
    "A penal colony's library, sparsely visited",
    "A transit shuttle between a station and an unscheduled destination",
    "A trade enclave with three currencies and a fourth in cipher",
    "A debris field over a contested planet",
    "A medical bay during a quiet shift",
    "A spaceport bar with a no-questions table",
    "A monastery on a low-grav moon",
    "A market on a station's bottom level, off the maps",
    "A salvage rig with a recovered alien artifact in storage",
    "A treaty signing in a microgravity hall",
    "A long-range observatory with one telescope detasked",
    "An ore-processor's lunch room mid-strike",
    "A privateer's bridge under a flag that may not be theirs",
    "A high-orbit prison module with a fresh body in cold storage",
    "A planetary command tent with an unscheduled visitor",
  ],

  catalysts: [
    "A treaty deadline lapses without ceremony",
    "A distress call repeats in a frequency band that shouldn't carry it",
    "A captain is recalled mid-mission with no explanation",
    "A long-dormant probe pings home with new data",
    "A border-station registry shows two ships of the same hull number",
    "A diplomat boards under a name not on the manifest",
    "A junior crewman finds a sealed locker without a tag",
    "A trader offers a fuel discount that closes a corridor",
    "A sleeper colony is found awake one cycle early",
    "A reactor core ratings begin to drift in formation",
    "A colony asks for evacuation despite no threat on record",
    "An old comrade arrives wearing the wrong service patch",
    "A salvage claim is contested by a polity nobody's heard of",
    "An automated relay starts editing messages",
    "A jump anomaly leaves the navigator without dead reckoning",
    "A friend asks to be smuggled past a check the friend should pass legally",
    "An admiral signs an order using a long-rescinded code",
    "A medical kit is found tampered with after issue",
    "A long-range scan picks up a fleet that left the books generations ago",
    "An ambassador's lieutenant defects mid-banquet",
    "An artifact responds to a crewman's name",
    "A registry update reclassifies a route from civilian to military",
    "A child of a known traitor turns up wanting passage off-world",
    "A factory ship arrives with too many lifepods, too few crew",
    "A high-clearance file accidentally cc's the protagonist",
    "A foreign drone is found inside the hull, dormant",
    "A crew member's prosthetic registers as a different individual",
    "A treaty broker offers preferential terms suddenly",
    "A scientific team withdraws funding from an active dig",
    "An off-the-books debt is called in by an old captain",
    "A ship's AI begins composing letters without authorisation",
    "A salvage rig finds a perfectly intact ship from before the Old War",
    "Customs is rerouted, leaving an honest captain holding paperwork that shouldn't be honest",
    "A station's gravity slips by a percent for a few seconds",
    "A passenger's identity chip flickers between two registries when read twice",
  ],

  sensory: {
    hear: [
      "Hull plating creaking through a thermal cycle",
      "A comms channel briefly carrying a voice it shouldn't",
      "Atmospheric scrubbers running at one-and-a-quarter speed",
      "A dock's pressure equalising in three stages",
      "Boots on grating, stopping one bay short",
      "A station bell announcing shift change two minutes early",
      "An alarm cancelled before it finishes its first cycle",
      "Subspace static with structure under it",
      "A junior officer's badge clicking in repeated nervousness",
      "A drone's manoeuvre thrusters in a sealed corridor",
      "Cryopod monitors humming a tone slightly off-spec",
      "A reactor whine settling, then re-rising",
      "A passenger humming an old anthem in a borrowed dialect",
      "A maintenance bay echoing faintly hours after work has stopped",
      "A reactor coolant leak hissing onto warm metal",
      "An automated voice apologising, then repeating the apology",
    ],
    see: [
      "Vacuum frost on the inside of a viewport",
      "A bulkhead label re-stencilled over an older designation",
      "Telltales on a panel that should be green flickering amber",
      "A long-range scope showing a star moving against the others",
      "A trailing dust contrail from a ship that should be cold",
      "A logo painted out and replaced — twice",
      "A recovery beacon strobing once a second",
      "A spacesuit hung in a locker, freshly dried",
      "A reflection in a polished bulkhead carrying an extra silhouette",
      "A captain wearing two service ribbons that don't go together",
      "Cargo seals broken and replaced with the wrong coloured tape",
      "Weather on a planet that doesn't have weather charts",
      "A drone hovering outside a viewport, lens facing in",
      "A datapad screen full of telemetry, one column anomalous",
      "Stars where there should be void",
      "A dog tag in a pocket that wasn't there yesterday",
    ],
    feel: [
      "Microgravity inertia in a turn",
      "Spin-grav at the edge of usable, knees noticing first",
      "Cold of a hull with one thin polymer between you and vacuum",
      "Tackiness of recently-dried sealant on bulkhead",
      "Hand-tools warming in calloused palms",
      "Vibration of a reactor through a steel deck",
      "Helmet-pressure pressing the brow when atmosphere is thin",
      "Coolant chill on the back of a hand from a leaking conduit",
      "Tension in a tether harness held at the right angle",
      "A datapad warming under regular access",
      "A standard chair in a non-standard ship",
      "An airlock cycling, change in ear pressure",
      "A stranger's gloved handshake with a tracker pulse",
      "Dry recycled air settling at the back of the throat",
      "A heads-up reticle drifting half a degree off true",
      "A jump engaging — that brief untethered moment",
    ],
    smell: [
      "Recycled air with a faint trace of solvent",
      "Hydraulic fluid hot under a panel",
      "Hydroponics deck tomato leaves",
      "Old propellant on a battered EVA suit",
      "Plasma cooling smell after a fire-fight drill",
      "Bulkhead paint outgassing in a new section",
      "Ration foil and its mass-produced contents",
      "Cargo bay grease and damp cardboard",
      "Cryosleep solution on someone newly woken",
      "Engineering grade lubricant",
      "Coffee made with reclaimed water",
      "An alien fruit, sweet, vaguely wrong",
      "Ozone after a relay arc",
      "Vacuum-cold on a returning suit",
      "Polymer of a freshly-sealed crate",
      "A diplomat's perfume, decanted from a real bottle",
    ],
  },

  belongings: [
    { category: "Standard issue",     items: ["comm badge", "ID chip", "multitool"] },
    { category: "Survival kit",       items: ["ration bars", "water purifier", "emergency beacon"] },
    { category: "Hacking",            items: ["data shard", "cipher key", "splice cable"] },
    { category: "Sidearms",           items: ["stun pistol", "vibroblade", "plasma cell"] },
    { category: "Medical",            items: ["hypospray", "bandages", "stimpack"] },
    { category: "Personal",           items: ["family holo", "ring", "datapad"] },
    { category: "Trade",              items: ["credit chits", "rare metals", "smuggled goods"] },
    { category: "Scientific",         items: ["scanner", "sample tubes", "recorder"] },
  ],
};
