/* Universal-Oracle / rpg / packs / steampunk.js
   Steampunk. Tone: brass and gaslight, society's seams visible, soot on the silk. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS.steampunk = {
  name: "Steampunk",
  tone: "Brass and gaslight, society's seams visible, soot on silk.",

  verbs: [
    "Address", "Apprehend", "Audit", "Bargain", "Beg leave", "Boast",
    "Bribe", "Calibrate", "Challenge", "Charter", "Collect", "Commission",
    "Confide", "Confiscate", "Conspire", "Counterfeit", "Court", "Decode",
    "Demand", "Demonstrate", "Disguise", "Embark", "Engage", "Engineer",
    "Escape", "Evade", "Expose", "Forge", "Frequent", "Furnish",
    "Hand-deliver", "Hire", "Impersonate", "Improvise", "Incite", "Indict",
    "Intercept", "Inveigle", "Investigate", "Inspect", "Lecture", "Manufacture",
    "Mortgage", "Notify", "Obtain", "Offer", "Patent", "Patrol",
    "Petition", "Pilfer", "Pledge", "Prevail", "Promise", "Publish",
    "Receive", "Recommend", "Refit", "Remit", "Remonstrate", "Reveal",
    "Riddle", "Rig", "Salute", "Scandalise", "Smuggle", "Sponsor",
    "Surveil", "Telegraph", "Threaten", "Toast", "Unveil", "Vouch",
  ],

  adjectives: [
    "Antiquated", "Articulated", "Bespoke", "Brass-fitted", "Burnished", "Calibrated",
    "Clockwork", "Clouded", "Coal-stained", "Compromised", "Conspicuous", "Counterfeit",
    "Crank-driven", "Decorated", "Deferential", "Dignified", "Discreet", "Engraved",
    "Etched", "Faded", "Filigreed", "Flickering", "Forged", "Furnaced",
    "Gaslit", "Gilded", "Grease-slick", "Heretical", "Hidden", "Honourable",
    "Hydraulic", "Impeccable", "Imperial", "Inscribed", "Iron-bound", "Lacquered",
    "Lacy", "Laudable", "Leather-bound", "Letter-pressed", "Liveried", "Mahogany",
    "Mechanical", "Minted", "Monocled", "Moustachioed", "Officious", "Oiled",
    "Overwound", "Paraffin-lit", "Patented", "Pinstriped", "Plated", "Pneumatic",
    "Proper", "Reckless", "Regulated", "Rigged", "Rusted", "Scandalous",
    "Sealed", "Smoke-blackened", "Soft-spoken", "Soot-stained", "Steam-driven", "Stiff-collared",
    "Sworn", "Tarnished", "Tinkered", "Top-hatted", "Velvet-lined", "Whirring",
  ],

  nouns: [
    "Academy", "Aether", "Airship", "Apothecary", "Apprentice", "Armoury",
    "Artificer", "Assignation", "Atelier", "Audience", "Automaton", "Banker",
    "Bell-pull", "Boiler", "Briefcase", "Brougham", "Cab", "Carriage",
    "Cartographer", "Cathedral", "Charge", "Charter", "Chronometer", "Cipher",
    "Clerk", "Club", "Coal", "Code", "Collector", "Comte",
    "Conductor", "Conference", "Contract", "Correspondence", "Crank", "Crown",
    "Cufflink", "Dame", "Decanter", "Diplomat", "Discovery", "Dispatch",
    "Dossier", "Duchess", "Earl", "Editor", "Engineer", "Engraving",
    "Envelope", "Espionage", "Estate", "Etiquette", "Exhibition", "Expedition",
    "Factory", "Favour", "Fellowship", "Footman", "Foundry", "Furnace",
    "Gala", "Gaslamp", "Gear", "Gentleman", "Governess", "Grant",
    "Guild", "Hansom", "Hat", "Inheritance", "Invitation", "Investor",
    "Inspector", "Investiture", "Jeweler", "Journal", "Lapel pin", "Lecture",
    "Letter", "Library", "Locomotive", "Lord", "Machinery", "Manifest",
    "Manufactory", "Marquess", "Match", "Memorandum", "Minister", "Monocle",
    "Naturalist", "Nobility", "Note", "Observatory", "Office", "Operation",
    "Order", "Patent", "Patron", "Pawn", "Penny dreadful", "Petticoat",
    "Pipe", "Piston", "Plot", "Pneumatic tube", "Policeman", "Postmaster",
    "Press", "Promenade", "Pulpit", "Punch card", "Quartermaster", "Quill",
    "Receipt", "Reception", "Reform", "Regiment", "Register", "Report",
    "Rival", "Salon", "Schematic", "Scientific society", "Scoundrel", "Seal",
    "Senator", "Sentinel", "Servant", "Shipping office", "Signet", "Sketch",
    "Smuggler", "Solicitor", "Sovereign", "Spy", "Steam", "Steamer",
    "Stipend", "Strike", "Subscription", "Surgeon", "Tailor", "Telegraph",
    "Telegram", "Theatre", "Theorem", "Toast", "Top hat", "Transcript",
    "Trust", "Underwriter", "Union", "Veil", "Verdict", "Vicar",
    "Visiting card", "Warrant", "Warship", "Watch", "Wharf", "Workshop",
  ],

  names: {
    male: [
      "Alistair", "Barnaby", "Cornelius", "Desmond", "Edgar", "Felix",
      "Gideon", "Horatio", "Ignatius", "Jasper", "Kingsley", "Lawrence",
      "Mortimer", "Nathaniel", "Octavius", "Percival", "Quentin", "Reginald",
      "Sebastian", "Theodore", "Uriah", "Vincent", "Wallace", "Yorick",
    ],
    female: [
      "Amelia", "Beatrix", "Cordelia", "Drusilla", "Evangeline", "Florence",
      "Genevieve", "Henrietta", "Isadora", "Josephine", "Katarine", "Lavinia",
      "Millicent", "Nora", "Ottilie", "Phoebe", "Quintessa", "Rosamund",
      "Seraphina", "Thomasina", "Ursula", "Violetta", "Winifred", "Zinnia",
    ],
    neutral: [
      "Ash", "Bray", "Crow", "Dane", "Ember", "Fen",
      "Grey", "Hale", "Iron", "Jett", "Kent", "Lark",
      "Mayhew", "North", "Orsen", "Pen", "Quill", "Rook",
      "Sterling", "Tarn", "Umber", "Vale", "Wren", "Yale",
    ],
  },

  locations: [
    "A gentlemen's club back room with a humidor and one empty chair",
    "An airship gondola with a charted route and unlisted cargo",
    "A railway terminus minutes before a private departure",
    "A pneumatic tube exchange overheard by a clerk",
    "A society's exhibition floor at midnight",
    "A foundry catwalk lit by furnace glare",
    "A telegraph office expecting a midnight cable",
    "An opera box rented under a counterfeit name",
    "A solicitor's chamber lined with chained ledgers",
    "A coffee house known for revolutionary leaflets",
    "An observatory in winter, lens uncapped",
    "A docks coffee-stall before the morning shifts",
    "A gentleman's tailor with a back fitting room and a side door",
    "A cabinet of natural curiosities, the curator absent",
    "A dredger's barge mid-river at slack tide",
    "A workshop where a single mechanism is being built oversize",
    "A clandestine printing press in a chapel basement",
    "A crematorium chimney that smokes off-schedule",
    "A naturalists' hall with one specimen newly missing",
    "An apothecary with the back room curtained",
    "An aldermanic chamber after a contested vote",
    "A fencing salle that doubles as a discreet meeting place",
    "A locksmith's shop accepting commissions by referral only",
    "A counting-house with a secondary set of books",
    "An undertaker's parlour with a coffin not yet ordered",
    "A municipal sewer crew's rest hut with surprisingly good tea",
    "A boiler-room office with a single occupied desk",
    "A widow's drawing room before the will is read",
    "A side-show tent with a barker who knows too much",
    "A shipping insurer's vaulted records room",
    "A mountain refit hangar for an experimental dirigible",
    "A glass-blower's studio with one piece under wraps",
    "A polite barricade on a strikebreaker's street",
  ],

  catalysts: [
    "An invitation arrives engraved with two seals where one would suffice",
    "A patent application is contested at the eleventh hour",
    "An airship's manifest is found to disagree with its cargo",
    "An automaton servant misaddresses a guest with a name from years ago",
    "A senior clubman is blackballed without explanation",
    "A telegram arrives unsigned, suggesting a meeting",
    "A nobleman's debt is purchased anonymously and called in",
    "A scientific paper is found to have been published twice with different conclusions",
    "A society discovery is rumoured to have been made by an outsider",
    "A government contract is leaked with a familiar signature on it",
    "A chambermaid arrives at the door with an unsealed letter",
    "An exhibition piece is reported missing — and then found in a different display",
    "A patent inspector calls without warning",
    "A gentleman's duel is staged at dawn over an absent third party",
    "A widow's pension is mysteriously paid in arrears",
    "An old apprentice returns from abroad with a knighthood",
    "A young woman of standing requests an unsuitable favour",
    "A foreign attaché requests a private interview",
    "A sealed will is unsealed early by court order",
    "An engineer is hired to defame a rival's design",
    "A clergyman is observed at an address he should not know",
    "A railway timetable changes overnight in a way that benefits one party",
    "An officer's commission is bought from under his nose",
    "A factory strike is suspiciously well-funded",
    "A university chair is offered as a polite removal",
    "A noted naturalist's collection is auctioned with one specimen withdrawn",
    "A charitable hospital's books are demanded by an outside auditor",
    "A whispered cipher is overheard at a salon",
    "A gentleman's footman is found dead in a cabinet of curiosities",
    "A diplomat's wife requests refuge from her husband",
    "A chemist's laboratory exhibits an explosion not in the records",
    "A solicitor offers a generous settlement to drop an inquiry",
    "An invented relative arrives, with documents in order",
    "A rival's daughter requests an interview without her father's knowledge",
  ],

  sensory: {
    hear: [
      "A pneumatic tube canister thumping into its receiver",
      "A pocket watch winding, then stopping",
      "Hooves on cobble at a measured pace",
      "An organ tested in a cold chapel",
      "A telegraph key ticking out a slow cipher",
      "Steam venting from a riveted boiler",
      "A coachman calling to his horses",
      "Coal being shovelled, three doors down",
      "Champagne corks across a marbled foyer",
      "A music hall song carrying out an alley",
      "A cane tapping a tempo in waiting",
      "The distant hiss of an airship venting",
      "A fountain pen scoring paper too hard",
      "A bell rope let go and swinging",
      "A sigh under a corseted breath",
      "Footmen in livery moving without a word",
    ],
    see: [
      "Soot fall against a white shirt cuff",
      "Gaslamp glare on wet stone",
      "A gentleman's pocket watch, lid open, no hands",
      "A clean pair of gloves left on a guest's chair",
      "An airship's shadow crossing the rooftops",
      "A calling card edged in mourning black",
      "Brass instruments arranged in formation",
      "A carriage's door crest hastily painted over",
      "A printer's ink-smudged thumbprint on a fresh page",
      "An automaton's eye, glass, fixed",
      "A skein of telegraph wires against a yellow sky",
      "A glass of port left, untouched, with the seal-ring beside it",
      "A signature blotted, then re-signed",
      "A society lady's veil lifted exactly halfway",
      "Coal smoke piled along the river",
      "An invitation engraved deeply enough to feel through fabric",
    ],
    feel: [
      "Starched linen against the throat",
      "Brass on the palm, warmer than expected",
      "Leather of a worn glove, supple from use",
      "Steam heat through a workshop floor",
      "A hat-pin catching cloth",
      "Soot grit between teeth after a railway tunnel",
      "Silk lining cool against a hot day's coat",
      "A signet ring's weight on a finger that didn't have one yesterday",
      "Steel of a swordstick disguised in a cane",
      "Cobblestone uneven through thin shoes",
      "Wax of a seal still soft to the thumb",
      "Engine vibration through a polished floorboard",
      "Cold of a brass doorknob in winter",
      "A handshake with too much force",
      "The lift of corseted breath",
      "A telegraph key under a fingertip, expectant",
    ],
    smell: [
      "Coal smoke and pipe tobacco",
      "Boot polish and lamp oil",
      "Sealing wax and pressed paper",
      "Damp wool overcoat and rain",
      "Leather upholstery and saddle soap",
      "Brass polish and engine grease",
      "Champagne and beeswax candles",
      "Black tea and lemon",
      "Saltpetre and stage smoke",
      "Woodsmoke and roasting chestnuts",
      "Hothouse orchids and powdered silk",
      "Printer's ink and newsprint",
      "Hot copper from a busy workshop",
      "Whisky and cigar leaf",
      "Ammonia from a back-alley fixative bath",
      "Camphor and silk laid up for the season",
    ],
  },

  belongings: [
    { category: "Gentleman's",        items: ["pocket watch", "calling cards", "monocle"] },
    { category: "Lady's",             items: ["lace fan", "vial of smelling salts", "hairpin"] },
    { category: "Mechanical tools",   items: ["brass instrument", "wrench", "screwdriver"] },
    { category: "Communication",      items: ["telegraph code book", "calling cards", "card case"] },
    { category: "Travel",             items: ["train ticket", "folded map", "brass compass"] },
    { category: "Concealed defense",  items: ["cane sword", "derringer", "brass knuckles"] },
    { category: "Spare parts",        items: ["brass gears", "oil can", "copper wire"] },
    { category: "Scholar's",          items: ["leather notebook", "fountain pen", "magnifying lens"] },
  ],
};
