/* Universal-Oracle / rpg / packs / weird-horror.js
   Weird horror. Tone: cosmic indifference, wrongness in small details, the lamp
   left on in a house no one is home to. */

window.GENRE_PACKS = window.GENRE_PACKS || {};
window.GENRE_PACKS["weird-horror"] = {
  name: "Weird Horror",
  tone: "Cosmic indifference, wrongness in small details.",

  verbs: [
    "Arrive", "Awaken", "Beckon", "Beg", "Bleed", "Bury",
    "Chant", "Confess", "Consume", "Convulse", "Crack", "Crawl",
    "Cry", "Curse", "Decay", "Disappear", "Dream", "Drown",
    "Echo", "Enter", "Erase", "Forget", "Forsake", "Glimpse",
    "Hum", "Kneel", "Listen", "Lure", "Mark", "Mistake",
    "Mourn", "Mutter", "Open", "Overhear", "Pray", "Reappear",
    "Recite", "Reflect", "Repeat", "Reveal", "Scream", "Seal",
    "Seek", "Shed", "Sicken", "Slip", "Sob", "Speak in tongues",
    "Spread", "Stalk", "Stare", "Suffocate", "Surrender", "Trespass",
    "Twist", "Unfold", "Unname", "Wake", "Weep", "Whisper",
  ],

  adjectives: [
    "Abandoned", "Aged", "Alien", "Asymmetric", "Backwards", "Black-veined",
    "Bone-cold", "Boneless", "Buried", "Cold", "Concealed", "Crawling",
    "Crooked", "Damp", "Decaying", "Drowned", "Elder", "Empty",
    "Faceless", "Faint", "Forbidden", "Forgotten", "Glassy", "Greying",
    "Half-seen", "Half-heard", "Heretical", "Hollow", "Howling", "Hungry",
    "Indifferent", "Listless", "Mottled", "Muffled", "Nameless", "Off",
    "Ornate", "Perforated", "Quiet", "Reflective", "Restless", "Rotten",
    "Salt-crusted", "Silent", "Slack", "Sleeping", "Slow", "Slumped",
    "Soft-spoken", "Stained", "Suspended", "Translucent", "Unfinished", "Unlit",
    "Unspoken", "Veiled", "Watching", "Waterlogged", "Whispering", "Withered",
    "Wrong",
  ],

  nouns: [
    "Altar", "Antiquarian", "Apparition", "Appendage", "Asylum", "Bell",
    "Belfry", "Body", "Bone", "Book", "Calendar", "Candle",
    "Cellar", "Chant", "Chapel", "Choir", "Cipher", "Cistern",
    "Confession", "Congregation", "Crypt", "Cult", "Curio", "Death",
    "Devotion", "Diary", "Door", "Dream", "Echo", "Eye",
    "Family", "Figure", "Fog", "Gate", "Glyph", "Grave",
    "Halo", "Hand", "Heretic", "Hour", "Hymn", "Icon",
    "Idol", "Inheritance", "Invitation", "Lamp", "Letter", "Library",
    "Liturgy", "Lodge", "Manuscript", "Mask", "Mirror", "Moth",
    "Mouth", "Name", "Neighbour", "Newspaper", "Note", "Order",
    "Pact", "Page", "Pew", "Photograph", "Portrait", "Priest",
    "Procession", "Psalm", "Ritual", "Saint", "Salt", "Seal",
    "Sermon", "Shadow", "Sign", "Silence", "Sinkhole", "Sleep",
    "Spire", "Stain", "Stillborn", "Stone", "Subterfuge", "Symbol",
    "Tongue", "Tooth", "Tower", "Vestment", "Vigil", "Voice",
    "Watcher", "Window", "Witness",
  ],

  names: {
    male: [
      "Alban", "Bartholomew", "Cyrus", "Damiel", "Edmund", "Fenwick",
      "Gideon", "Hollis", "Ignatius", "Jeremiah", "Kasimir", "Lazarus",
      "Marcellus", "Nathaniel", "Obed", "Percival", "Quentin", "Reuben",
      "Silas", "Thaddeus", "Ulric", "Vance", "Wendell", "Zachariah",
    ],
    female: [
      "Adelaide", "Beatrice", "Constance", "Demelza", "Eulalia", "Felicity",
      "Genevieve", "Hester", "Imelda", "Jezebel", "Keziah", "Lavinia",
      "Mehetabel", "Nadia", "Octavia", "Persephone", "Querida", "Rosalind",
      "Sibyl", "Tabitha", "Ursula", "Vespera", "Winifred", "Zenobia",
    ],
    neutral: [
      "Ash", "Briar", "Crow", "Dusk", "Echo", "Fen",
      "Grey", "Hush", "Ink", "Joss", "Kestrel", "Linden",
      "Marrow", "Nyx", "Oriel", "Penn", "Quill", "Reed",
      "Salem", "Tide", "Umber", "Vale", "Wren", "Zephyr",
    ],
  },

  locations: [
    "An attic where the dust pattern doesn't match the floor",
    "A village pub where everyone falls silent at the same minute each evening",
    "A church with thirteen pews and an extra hymn book",
    "A library after closing, with one window lit",
    "A tide pool that does not change with the tide",
    "A house where every clock is ten minutes wrong, all by the same ten minutes",
    "A quarry that produces no echoes",
    "A bed-and-breakfast with a guestbook in another hand",
    "A lighthouse with the lamp out but the keeper present",
    "A cellar accessed through a door that doesn't open from inside",
    "A railway halt with no timetable and one waiting figure",
    "A reading room of an antiquarian society",
    "A salt marsh at the wrong tide",
    "A photographer's studio whose negatives all carry an extra figure",
    "A school assembly where no adult is present",
    "A bog with stakes set out at intervals",
    "A graveyard where the dates skip a year",
    "A coastal hotel between seasons",
    "A printing press still warm",
    "A monastery library with one chained book",
    "A fairground after closing",
    "A funeral parlour expecting a coffin no one ordered",
    "A roadside diner whose menu lists items no one will sell",
    "A widow's cottage with three place settings",
    "A theatre rehearsing a play no one wrote",
    "A hospital wing kept dim past visiting hours",
    "A river bend where the water turns the wrong way",
    "A cathedral crypt with a freshly-broken seal",
    "An abandoned summer camp in autumn",
    "A radio room receiving calls in the wrong language",
    "An estate's hedge maze that has grown extra paths",
  ],

  catalysts: [
    "A neighbour's dog refuses the house",
    "A diary in the family hand stops mid-sentence in 1903",
    "A small saint's statue is found weeping salt water",
    "A child draws someone always standing behind themselves",
    "A wedding photograph develops a fourth person",
    "Mass is held on a day that doesn't exist",
    "An old aunt's letter arrives postmarked years before her death",
    "A locked door is found unlocked, and warm",
    "Birds gather on the roof and do not call",
    "An invitation arrives addressed in one's own handwriting",
    "A lullaby is heard in a shuttered nursery",
    "Salt is found in a perfect ring around the bed",
    "A long-buried name surfaces in a casual conversation",
    "The neighbour's lights go out together at 3:14 every night",
    "A rosary is found bitten through",
    "A childhood friend is not remembered by anyone else",
    "An old wedding ring shows up without its owner",
    "A photograph is found in which the wallpaper isn't right",
    "A mirror reflects the room from yesterday",
    "A fellow boarder's shoes are dry every morning despite the rain",
    "A heretical pamphlet is found shelved among the family bibles",
    "A clergyman calls without being summoned",
    "An old carved sign reappears after years gone",
    "Children sing a counting rhyme that doesn't end",
    "A sleepless townsfolk all dream the same hill",
    "A forgotten cousin shows up — and is recognised by everyone except the dreamer",
    "Animals stop coming near the property",
    "An old hymn is sung in a language no one in the choir reads",
    "A friend's reflection lingers a beat too long",
    "A long-dead relative is reported seen at a funeral",
    "A lighthouse beam goes the wrong direction for an evening",
    "A name is whispered into the household at night, three times",
    "A signed photograph appears in a museum collection of an event no one attended",
    "A door appears in a wall that wasn't there",
    "A paragraph in the parish register is in another hand, fresh ink",
  ],

  sensory: {
    hear: [
      "A hymn sung in another room, slightly behind the words",
      "A distant bell tolling at the wrong hour",
      "A clock ticking out of time with itself",
      "Rain that doesn't quite hit the windows",
      "Whispering behind walls when there are no walls there",
      "A child counting, getting only to nine",
      "Footsteps approaching, never arriving",
      "Wind in chimneys with no wind outside",
      "A door slowly latching itself",
      "A choir, always one voice extra",
      "The hush that comes before a thunderclap, with no thunder",
      "Floorboards setting themselves",
      "A cat purring where there is no cat",
      "Pages turning in a closed book",
      "An owl repeating only one note",
      "A wedding bell at three in the morning",
    ],
    see: [
      "An empty pew with a worn spot at one end",
      "A photograph slowly shifting expression",
      "A reflection that pauses before following",
      "Water in a glass climbing slightly up one side",
      "A figure in the upstairs window, gone when looked back at",
      "Salt scattered in a pattern that resembles a script",
      "Candlewicks all listing toward one wall",
      "A door open by exactly the same width every morning",
      "An infant in a portrait whose eyes have darkened",
      "A hand mark on a freshly painted ceiling",
      "Stars that aren't quite where they should be",
      "An animal staring at a corner",
      "A body of water reflecting a sky that isn't above it",
      "A footprint set in dust where there has been no foot",
      "A line in dust slowly dividing the room",
      "A fly that doesn't move in a closed jar",
    ],
    feel: [
      "A draft from a sealed room",
      "The skin's certainty of being looked at",
      "Hair on the arm responding to no draft",
      "Cold on one cheek only",
      "A sudden softness in the floor",
      "Damp under a bed that has been dry",
      "A ring tightening, briefly",
      "Pressure behind the eyes, gentle",
      "Warmth on a stair that no one has stood on",
      "A heartbeat heard rather than felt, then felt rather than heard",
      "A quick chill when a name is said out loud",
      "Static along the scalp, like a thunderhead approaching",
      "A small slick patch on a polished pew",
      "Cobweb where there should be no cobweb",
      "Faint vibration through a still floor",
      "An object in a coat pocket that wasn't there",
    ],
    smell: [
      "Lilies and damp paper",
      "Communion wine and old candle smoke",
      "Salt water and stone",
      "Camphor and dried ink",
      "A smell like a forgotten hospital ward",
      "Wet wool and incense",
      "Bog moss and sweetness",
      "Brass polish and decay",
      "Rain on warm flagstones",
      "Old furs that haven't been worn in a generation",
      "Beeswax and tannic dust",
      "Iron filings and copper",
      "A cellar that has been recently swept",
      "Dust risen for no reason",
      "Old roses that should be dry, still wet",
      "Tallow and graveyard turf",
    ],
  },

  belongings: [
    { category: "Antiquarian",        items: ["leather journal", "old foreign coins", "a faded photograph"] },
    { category: "Religious tokens",   items: ["rosary", "vial of holy water", "prayer book"] },
    { category: "Investigative",      items: ["pocket notebook", "fountain pen", "magnifying glass"] },
    { category: "Personal",           items: ["silver locket", "lace handkerchief", "signet ring"] },
    { category: "Travel",             items: ["train ticket stub", "folded map", "brass compass"] },
    { category: "Defensive",          items: ["silver knife", "pouch of salt", "wooden cross"] },
    { category: "Memory",             items: ["child's wooden toy", "faded letter", "daguerreotype"] },
    { category: "Scholar's",          items: ["leather-bound book", "magnifying glass", "ink-stained notebook"] },
  ],
};
