#!/usr/bin/env python3
"""
shuffle.py — produce a depersonalised alternative deck by data-shuffling
each field independently across records.

The set of values in each field stays identical; only the row-level
combinations change. Statistically the deck is the same — column-wise
distributions, frequencies, value sets are preserved — but no row carries
its original combination of catalyst, location, virtue, vice, names, etc.

Usage:
    python app/extract/shuffle.py app/cards.js app/cards-alternative.js
    # or, piped:
    python app/extract/shuffle.py < app/cards.js > app/cards-alternative.js

Reads `window.GMA_CARDS = [...]`, writes `window.GMA_CARDS_ALTERNATIVE = [...]`.

The output is a derivative of your local cards.js. Keep it git-ignored —
the .gitignore in this repo already excludes `cards-alternative.js`.
"""

import json
import random
import re
import sys
from pathlib import Path

# Fields to permute. `id` is left untouched so card numbering still maps
# 1..N. Add or remove fields here to change which dimensions get shuffled.
SHUFFLE_FIELDS = [
    "difficulty",
    "odds",
    "dice",
    "rune",
    "element",
    "event",
    "sensory",
    "tags",
    "scatter",
    "belongings",
    "names",
    "catalyst",
    "location",
    "virtue",
    "vice",
]


def parse_js(text):
    """Extract the array literal from `window.GMA_CARDS = [ ... ];`."""
    m = re.search(r"window\.GMA_CARDS\s*=\s*(\[.*?\])\s*;", text, re.DOTALL)
    if not m:
        raise ValueError("Couldn't find `window.GMA_CARDS = [...]` in input")
    return json.loads(m.group(1))


def shuffle_deck(cards, fields=SHUFFLE_FIELDS, seed=None):
    """Return a new list of cards with each named field independently permuted
    across records. `id` (and any field not in `fields`) is preserved in row order."""
    if not cards:
        return []
    rng = random.Random(seed)
    out = [dict(c) for c in cards]  # shallow copies; we'll overwrite shuffled fields
    n = len(cards)
    for field in fields:
        values = [c.get(field) for c in cards]
        order = list(range(n))
        rng.shuffle(order)
        for dst, src in enumerate(order):
            out[dst][field] = values[src]
    return out


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    flags = {a for a in argv[1:] if a.startswith("--")}
    seed = None
    for f in flags:
        if f.startswith("--seed="):
            seed = int(f.split("=", 1)[1])

    if len(args) >= 2:
        text = Path(args[0]).read_text(encoding="utf-8")
        out_path = Path(args[1])
    elif len(args) == 1:
        text = Path(args[0]).read_text(encoding="utf-8")
        out_path = None
    else:
        text = sys.stdin.read()
        out_path = None

    cards = parse_js(text)
    shuffled = shuffle_deck(cards, seed=seed)

    payload = (
        "/* GMA / cards-alternative.js — generated by shuffle.py */\n"
        "/* Each field is independently permuted across records relative to\n"
        "   cards.js. The set of values in each column is identical; row-level\n"
        "   combinations are scrambled. Re-run shuffle.py for a fresh shuffle. */\n"
        "window.GMA_CARDS_ALTERNATIVE = " +
        json.dumps(shuffled, indent=2, ensure_ascii=False) +
        ";\n"
    )

    if out_path:
        out_path.write_text(payload, encoding="utf-8")
        print(f"info: shuffled {len(cards)} cards -> {out_path}", file=sys.stderr)
    else:
        sys.stdout.write(payload)
        print(f"info: shuffled {len(cards)} cards", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv)
